### ISSUE TITLE
NoReverseMatch at /

### ISSUE THREAD

**Issue by keinen87** [keinen87/blog#2]
До добавления вью логина коммит WIP 766e9d2351e467767af6db5d34df1de3a7a7ddb5
Добавил вью [логина](https://github.com/keinen87/blog/blob/auth/blog/website/views/views_reg.py)
Почему вот такая ошибка
![screenshot - 06 06 2016 - 11 01 15](https://cloud.githubusercontent.com/assets/14131872/15814195/09711ff4-2bd6-11e6-96e3-71936479d35b.png)
@spacediver

**Comment by sutyrin** [comment]
Попытка сделать reverse для view с именем login без параметров?

2016-06-06 10:10 GMT+03:00 keinen87 notifications@github.com:

> До добавления вью логина коммит WIP 766e9d2
> https://github.com/keinen87/blog/commit/766e9d2351e467767af6db5d34df1de3a7a7ddb5
> Добавил вью логина
> https://github.com/keinen87/blog/blob/auth/blog/website/views/views_reg.py
> Почему вот такая ошибка
> [image: screenshot - 06 06 2016 - 11 01 15]
> https://cloud.githubusercontent.com/assets/14131872/15814195/09711ff4-2bd6-11e6-96e3-71936479d35b.png
> @spacediver https://github.com/spacediver
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/keinen87/blog/issues/2, or mute the thread
> https://github.com/notifications/unsubscribe/ABIxCbvm7MUVXxch-rgnnmBWDQYP5m0Qks5qI8fugaJpZM4Iunf8
> .

## 

Павел Сутырин || Pavel Sutyrin
skype: pavel_sutyrin || cellphone: +7 903 592 76 87 ||
ssh-rsa: http://j.mp/sutyrin-ssh
